services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--username", "root", "--password", "admin123", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  node-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      DEPLOYMENT: docker
      DB_DOCKER: mongodb://root:admin123@mongo:27017/todo_list?authSource=admin
      PORT: 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:

